<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Cida.Core\Cida.Core.csproj" />
    <ProjectReference Include="..\Cida.Platform\Cida.Platform.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <OutputType>WinExe</OutputType>
    <AssemblyName>Cida</AssemblyName>
    <RootNamespace>Cida.Desktop</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Nullable>enable</Nullable>
  </PropertyGroup>


</Project>
